module.exports = [
	{
		name: 'Wallace',
		level_required: "0",
		gold_cost: "0",
		gem_cost: "0",
		title: 'Blacksmith',
		blueprint_unlocks: ['squiresword'],
	},
	{
		name: "Allan",
		level_required: "3",
		gold_cost: "2,500",
		gem_cost: "50",
		title: "Carpenter",
		blueprint_unlocks: ["Cudgel", "Carved Branch"],
	},
	{
		name: "Roxanne",
		level_required: "0",
		gold_cost: "0",
		gem_cost: "0",
		title: "Engineer",
		blueprint_unlocks: ["Light Crossbow", "Pellet Gun"],
	},
	{
		name: "Maribel",
		level_required: "5",
		gold_cost: "10,000",
		gem_cost: "200",
		title: "Herbalist",
		blueprint_unlocks: ["Mintyleaf Herb"],
	},
	{
		name: "Katarina",
		level_required: "20",
		gold_cost: "250,000",
		gem_cost: "600",
		title: "Jeweler",
		blueprint_unlocks: ["Iron Ring"],
	},
	{
		name: "Theodore",
		level_required: "30",
		gold_cost: "1,000,000",
		gem_cost: "1,500",
		title: "Master",
		blueprint_unlocks: [],
	},
	{
		name: "Freyja",
		level_required: "25",
		gold_cost: "500,000",
		gem_cost: "1,000",
		title: "Priestess",
		blueprint_unlocks: ["Memento", "Ram Spirit"],
	},
	{
		name: "Evelyn",
		level_required: "0",
		gold_cost: "0",
		gem_cost: "0",
		title: "Scholar",
		blueprint_unlocks: ["Baton", "Chipped Runestone"],
	},
	{
		name: "Julia",
		level_required: "2",
		gold_cost: "0",
		gem_cost: "0",
		title: "Tailor",
		blueprint_unlocks: ["Leather Gloves", "Shirt", "Leather Boots"],
	},
	{
		name: "Grimar",
		level_required: "12",
		gold_cost: "50,000",
		gem_cost: "300",
		title: "Wizard",
		blueprint_unlocks: ["Scroll of Sparks"],
	}
]
