export const frontmatter = {
  Name: "Gladius",
  Type: "Sword",
  "Unlock Prerequisite": "---",
  "Research Scrolls": 3,
  Tier: 3,
  Value: 670,
  "Crafting Time (seconds)": 140,
  "Crafting Time (formatted)": "0:02:20",
  "Value / Crafting Time": 4.79,
  "Merchant XP": "1,200",
  "Worker XP": 18,
  "Required Worker": "Blacksmith",
  "Worker Level": 2,
  "Required Worker__1": "---",
  "Worker Level__1": "---",
  iron: 14,
  wood: "---",
  leather: "---",
  herbs: "---",
  steel: "---",
  ironwood: "---",
  fabric: "---",
  oil: "---",
  Component: "Iron Pine Cone",
  "Component Quality": "---",
  "Amount Needed": 2,
  Component__1: "---",
  "Component Quality__1": "---",
  "Amount Needed__1": "---",
  ATK: 52,
  DEF: "---",
  HP: "---",
  "Crafting Upgrade 1": "x1.25 Value Increase",
  "Crafts Needed": 9,
  "Crafting Upgrade 2": "Blueprint: Cutlass",
  "Crafts Needed__1": 22,
  "Crafting Upgrade 3": "-25% Craft Time Reduction",
  "Crafts Needed__2": 40,
  "Crafting Upgrade 4": "-4 Iron Spent",
  "Crafts Needed__3": 65,
  "Crafting Upgrade 5": "Quality Chance x3",
  "Crafts Needed__4": 100,
  "Ascension Upgrade 1": "-1 Iron Pine Cone Spent",
  "Shards Needed": 10,
  "Ascension Upgrade 2": "+10% Multicraft Chance",
  "Shards Needed__1": 10,
  "Ascension Upgrade 3": "Quality Chance x3",
  "Shards Needed__2": 10,
  "Discount Energy": 20,
  "Surcharge Energy": 45,
  "Suggest Energy": 25,
  "Speed Up Energy": 70,
}
