export default {
  name: "Oscar",
  level_required: "0",
  gold_cost: "0",
  gem_cost: "0",
  title: "Emerald Inn",
  blueprint_unlocks: [],
  description:
    "Investing in the Emerald Inn will speed up the healing rate of Heroes.",
  bonus: "Increases Hero Resting Speed.",
  prerequisite: "---",
  levels: [
    {
      level: 1,
      time: "---",
      seconds: 0,
      investments: { gold: 100, gems: 2 },
      cost: 1000,
      effect: "---",
    },
    {
      level: 2,
      time: "15m",
      seconds: 900,
      investments: { gold: 200, gems: 4 },
      cost: 4000,
      effect: "Howling Woods Rest Time: 90%",
    },
    {
      level: 3,
      time: "1h",
      seconds: 3600,
      investments: { gold: 400, gems: 6 },
      cost: 12000,
      effect: "Howling Woods Rest Time: 75%",
    },
    {
      level: 4,
      time: "1h 30m",
      seconds: 5400,
      investments: { gold: 1000, gems: 10 },
      cost: 60000,
      effect: "Aurora Caves Rest Time: 90%",
    },
    {
      level: 5,
      time: "2h",
      seconds: 7200,
      investments: { gold: 2200, gems: 20 },
      cost: 198000,
      effect: "Aurora Caves Rest Time: 75%",
    },
    {
      level: 6,
      time: "3h",
      seconds: 10800,
      investments: { gold: 2800, gems: 23 },
      cost: 300000,
      effect: "Whispering Bog Rest Time: 90%",
    },
    {
      level: 7,
      time: "4h",
      seconds: 14400,
      investments: { gold: 8000, gems: 30 },
      cost: 1425000,
      effect: "Whispering Bog Rest Time: 75%",
    },
    {
      level: 8,
      time: "5h",
      seconds: 18000,
      investments: { gold: 12000, gems: 35 },
      cost: 3200000,
      effect: "Barran Wastes Rest Time: 90%",
    },
    {
      level: 9,
      time: "7h",
      seconds: 25200,
      investments: { gold: 50000, gems: 40 },
      cost: 19800000,
      effect: "Barran Wastes Rest Time: 75%",
    },
    {
      level: 10,
      time: "11h 40m",
      seconds: 42000,
      investments: { gold: 150000, gems: 50 },
      cost: 70000000,
      effect: "Sun God's Tomb Rest Time: 90%",
    },
    {
      level: 11,
      time: "17h 20m",
      seconds: 62400,
      investments: { gold: 300000, gems: 60 },
      cost: '---',
      effect: "Sun God's Tomb Rest Time: 75%",
    },
  ],
  resource: "---",
}
